// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbecipfjuzmizsikmtqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNiZWNpcGZqdXptaXpzaWttdHFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTM3NDksImV4cCI6MjA2NDYyOTc0OX0.a7Z1-SLgdtKDyJMQSqbZgBs0yNK7DQ0GTP6p2FYY_fE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);